version: "3.7"
services:
  resiliosync:
    container_name: resiliosync
    restart: unless-stopped
    expose:
      - 8888
    image: linuxserver/resilio-sync
    volumes:
      - /media/DockerData/resiliosync/config:/config
      - /media/Data/ResilioSync:/sync
      - /media/Data/ResilioSync/Downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - CONTEXT_PATH=/resiliosync

  crashplan:
    container_name: crashplan
    restart: unless-stopped
    network_mode: host
    image: jrcs/crashplan
    environment:
      - MAX_MEMORY_MB=4096
      - TZ=${TZ}
    volumes:
      - /media/DockerData/crashplan/config:/var/crashplan

  duplicati:
    container_name: duplicati
    restart: unless-stopped
    image: linuxserver/duplicati
    # build: duplicati
    expose:
      - 8200
    volumes:
      - /media/DockerData/duplicati/config:/config
      - /media/Backups:/backups
      - /media/Data:/source
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}

  couchpotato:
    container_name: couchpotato
    restart: unless-stopped
    build: couchpotato
    expose:
      - 5050
    volumes:
      - /media/DockerData/sabnzbd/config:/sabnzbdconfig
      - /media/DockerData/transmission/config:/transmissionconfig
      - /media/DockerData/hydra2/config:/hydra2config
      - /media/DockerData/couchpotato/config:/config
      - /media/DockerDownloads:/downloads
      - incomplete-nzbs:/incomplete-nzbs
      - nzbtomedia:/nzbtomedia
    depends_on:
      - transmission
      - sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}

  # calibre:
  #   image: linuxserver/calibre
  #   container_name: calibre
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=${TZ}
  #   volumes:
  #     - /media/DockerData/calibre/config:/config
  #   expose:
  #     - 8080
  #   restart: unless-stopped

  # guacd:
  #   image: linuxserver/guacd
  #   container_name: guacd
  #   expose:
  #     - 4822
  #   restart: unless-stopped

  ddclient:
    container_name: ddclient
    restart: unless-stopped
    build: ddclient
    #  image: yaronr/ddclient:latest
    environment:
      - DDNS_SERVER=update.dedyn.io
      - DDNS_DOMAIN=dedyn.io
      - DDNS_PROTOCOL=dyndns2

  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - VALIDATION=http
      - DHLEVEL=2048
    volumes:
      - /media/DockerData/letsencrypt/config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  # funkwhale:
  #   container_name: funkwhale
  #   restart: unless-stopped
  #   image: funkwhale/all-in-one
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - NESTED_PROXY=1
  #   volumes:
  #     - /media/DockerData/funkwhale:/data
  #     - /media/Data/Share/Music:/music:ro
  #   expose:
  #     - "5000"

  plex:
    container_name: plex
    restart: unless-stopped
    network_mode: host
    image: linuxserver/plex
    volumes:
      - /media/DockerData/plex/config:/config
      - /media/DockerDownloads:/downloads
    environment:
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000

  samba:
    container_name: samba
    image: dperson/samba
    network_mode: host
    restart: unless-stopped
    environment:
      - TZ=${TZ}

  sickchill:
    container_name: sickchill
    restart: unless-stopped
    build: sickchill
    expose:
      - 8081
    volumes:
      - /media/DockerData/sickchill/config:/config
      - /media/DockerData/hydra2/config:/hydra2config
      - /media/DockerDownloads:/downloads
      - /media/DockerData/sabnzbd/config:/sabnzbdconfig
      - incomplete-nzbs:/incomplete-nzbs
      - nzbtomedia:/nzbtomedia
    depends_on:
      - transmission
      - sabnzbd
      - hydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}

  jackett:
    build: jackett
    #image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - RUN_OPTS=run options here #optional
    volumes:
      - /media/DockerData/jackett/config:/config
    #   - path to blackhole:/downloads
    expose:
      - 9117
    restart: unless-stopped

  hydra2:
    #image: linuxserver/hydra2
    build: hydra2
    container_name: hydra2
    expose:
      - 5076
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /media/DockerData/hydra2/config:/config
      - /media/DockerData/jackett/config:/jackettconfig
      - /media/DockerDownloads:/downloads
      - /media/DockerData/sabnzbd/config:/sabnzbdconfig
    restart: unless-stopped

  sabnzbd:
    container_name: sabnzbd
    build: sabnzbd
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - /media/DockerData/sabnzbd/config:/config
      - /media/DockerDownloads:/downloads
      - incomplete-nzbs:/incomplete-nzbs # The reason this is local to container is to workaround problems with long file names
      - nzbtomedia:/nzbtomedia
      - sabnzbdfuture:/config/admin/future
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}

  airsonic:
    image: linuxserver/airsonic
    #build:
    # context: ./airsonic
    container_name: airsonic
    restart: unless-stopped
    volumes:
      - /media/DockerData/airsonic/config:/config
      - /media/data/Share/Music:/music
    expose:
      - 4040
    environment:
      - PUID=1000
      - PGID=1000
      - JAVA_OPTS=-Xmx700m
      - CONTEXT_PATH=/airsonic
      - TZ=${TZ}

  nextcloud:
    build:
      context: ./nextcloud
    #image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /media/DockerData/nextcloud/config:/config
      - /media/DockerData/nextcloud/data:/data
      - /media/sf_Data/Data/Share:/data/Share
      - /media/DockerDownloads:/data/DockerDownloads
    expose:
      - 443
    restart: unless-stopped

  timemachine-avahi:
    container_name: timemachine-avahi
    restart: unless-stopped
    network_mode: host
    build: timemachine-avahi
    environment:
      - TZ=${TZ}

  transmission:
    container_name: transmission
    restart: unless-stopped
    build: transmission
    #network_mode: host # disables transmission hostname from other containers.. referring to transmission by localhost IP
    # not really gonna help with anything, since my Vagrant is NATTed
    #TODO: I need a uPNP capable redirector for my exposed ports, and also a solution for vagrant NAT.
    # This also causes massive problems, because I can't communicate internally with sickchill, etc. So disabling.
    expose:
      - 9091
    ports:
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - /media/DockerData/transmission/config:/config
      - /media/DockerDownloads:/downloads
      - nzbtomedia:/nzbtomedia
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}

  timemachine:
    container_name: timemachine
    restart: unless-stopped
    image: odarriba/timemachine
    ports:
      - 548:548
      - 636:636
    depends_on:
      - timemachine-avahi
    environment:
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000

  webdav:
    container_name: webdav
    restart: unless-stopped
    #image: NoahO/webdav
    build: webdav
    depends_on:
      - letsencrypt
    volumes:
      - /media/DockerData/webdav/data:/media/webdav
    expose:
      - 8080
    environment:
      - TZ=${TZ}
      - UID=1000

volumes:
  incomplete-nzbs:
  nzbtomedia:
  sabnzbdfuture: #Needed to work around long file names in windows.
